# Form implementation generated from reading ui file 'CommunityLevelsScreen.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(1126, 902)
        Dialog.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(58, 58, 58);")
        self.back_butt = QtWidgets.QPushButton(parent=Dialog)
        self.back_butt.setGeometry(QtCore.QRect(970, 50, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back_butt.setFont(font)
        self.back_butt.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/Back_butt.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.back_butt.setIcon(icon)
        self.back_butt.setIconSize(QtCore.QSize(100, 100))
        self.back_butt.setFlat(True)
        self.back_butt.setObjectName("back_butt")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(340, 30, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(460, 80, 351, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(48)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.list_of_levels = QtWidgets.QListWidget(parent=Dialog)
        self.list_of_levels.setGeometry(QtCore.QRect(40, 280, 1051, 501))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.list_of_levels.setFont(font)
        self.list_of_levels.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.list_of_levels.setObjectName("list_of_levels")
        self.play_butt = QtWidgets.QPushButton(parent=Dialog)
        self.play_butt.setGeometry(QtCore.QRect(960, 800, 91, 81))
        self.play_butt.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Images/Play_butt.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.play_butt.setIcon(icon1)
        self.play_butt.setIconSize(QtCore.QSize(80, 80))
        self.play_butt.setFlat(True)
        self.play_butt.setObjectName("play_butt")
        self.finder_edit = QtWidgets.QLineEdit(parent=Dialog)
        self.finder_edit.setGeometry(QtCore.QRect(140, 229, 791, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.finder_edit.setFont(font)
        self.finder_edit.setObjectName("finder_edit")
        self.find = QtWidgets.QPushButton(parent=Dialog)
        self.find.setGeometry(QtCore.QRect(960, 232, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.find.setFont(font)
        self.find.setObjectName("find")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 235, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Blind "))
        self.label_2.setText(_translate("Dialog", "Typing"))
        self.find.setText(_translate("Dialog", "Найти"))
        self.label_3.setText(_translate("Dialog", "Название уровня:"))
