# Form implementation generated from reading ui file 'CreateNewLevelWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(1126, 900)
        Dialog.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(58, 58, 58);")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(330, 20, 311, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(450, 120, 351, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(48)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(60, 250, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.new_level_name = QtWidgets.QLineEdit(parent=Dialog)
        self.new_level_name.setGeometry(QtCore.QRect(170, 260, 901, 20))
        self.new_level_name.setObjectName("new_level_name")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(90, 310, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.new_level_text = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.new_level_text.setGeometry(QtCore.QRect(170, 300, 901, 431))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.new_level_text.setFont(font)
        self.new_level_text.setObjectName("new_level_text")
        self.save_new_level_butt = QtWidgets.QPushButton(parent=Dialog)
        self.save_new_level_butt.setGeometry(QtCore.QRect(880, 790, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.save_new_level_butt.setFont(font)
        self.save_new_level_butt.setObjectName("save_new_level_butt")
        self.back_butt = QtWidgets.QPushButton(parent=Dialog)
        self.back_butt.setGeometry(QtCore.QRect(1000, 30, 101, 101))
        self.back_butt.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/Back_butt.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.back_butt.setIcon(icon)
        self.back_butt.setIconSize(QtCore.QSize(100, 100))
        self.back_butt.setFlat(True)
        self.back_butt.setObjectName("back_butt")
        font = QtGui.QFont()
        font.setPointSize(18)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Blind "))
        self.label_2.setText(_translate("Dialog", "Typing"))
        self.label_3.setText(_translate("Dialog", "Название:"))
        self.label_4.setText(_translate("Dialog", "Текст:"))
        self.save_new_level_butt.setText(_translate("Dialog", "Сохранить"))
