# Form implementation generated from reading ui file 'EndGameScreen.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(1123, 901)
        Dialog.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(58, 58, 58);")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(470, 100, 351, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(48)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(350, 50, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(100, 320, 961, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.time_lable = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.time_lable.setFont(font)
        self.time_lable.setText("")
        self.time_lable.setObjectName("time_lable")
        self.verticalLayout.addWidget(self.time_lable)
        self.speed_lable = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.speed_lable.setFont(font)
        self.speed_lable.setText("")
        self.speed_lable.setObjectName("speed_lable")
        self.verticalLayout.addWidget(self.speed_lable)
        self.accuracy_lable = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.accuracy_lable.setFont(font)
        self.accuracy_lable.setText("")
        self.accuracy_lable.setObjectName("accuracy_lable")
        self.verticalLayout.addWidget(self.accuracy_lable)
        self.back_butt = QtWidgets.QPushButton(parent=Dialog)
        self.back_butt.setGeometry(QtCore.QRect(960, 60, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.back_butt.setFont(font)
        self.back_butt.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Images/Back_butt.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.back_butt.setIcon(icon)
        self.back_butt.setIconSize(QtCore.QSize(100, 100))
        self.back_butt.setFlat(True)
        self.back_butt.setObjectName("back_butt")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Typing"))
        self.label.setText(_translate("Dialog", "Blind "))
