# Form implementation generated from reading ui file 'GameScreen.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(1122, 900)
        Dialog.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(58, 58, 58);")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(550, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(510, 10, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.game_text = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.game_text.setEnabled(False)
        self.game_text.setGeometry(QtCore.QRect(40, 90, 1061, 361))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.game_text.setFont(font)
        self.game_text.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.game_text.setReadOnly(True)
        self.game_text.setObjectName("game_text")
        self.user_text = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.user_text.setGeometry(QtCore.QRect(40, 470, 1061, 401))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.user_text.setFont(font)
        self.user_text.setFocusPolicy(QtCore.Qt.FocusPolicy.ClickFocus)
        self.user_text.setObjectName("user_text")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Typing"))
        self.label.setText(_translate("Dialog", "Blind "))
