# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1125, 901)
        MainWindow.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(58, 58, 58);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 50, 311, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.exit_butt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_butt.setGeometry(QtCore.QRect(510, 630, 121, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.exit_butt.setFont(font)
        self.exit_butt.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.exit_butt.setStyleSheet("color: rgb(255, 148, 60);")
        self.exit_butt.setFlat(True)
        self.exit_butt.setObjectName("exit_butt")
        self.new_game_butt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.new_game_butt.setGeometry(QtCore.QRect(480, 330, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.new_game_butt.setFont(font)
        self.new_game_butt.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.new_game_butt.setMouseTracking(False)
        self.new_game_butt.setStyleSheet("color: rgb(255, 148, 60);")
        self.new_game_butt.setFlat(True)
        self.new_game_butt.setObjectName("new_game_butt")
        self.create_level_butt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.create_level_butt.setGeometry(QtCore.QRect(420, 430, 311, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.create_level_butt.setFont(font)
        self.create_level_butt.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.create_level_butt.setStyleSheet("color: rgb(255, 148, 60);")
        self.create_level_butt.setAutoDefault(True)
        self.create_level_butt.setDefault(False)
        self.create_level_butt.setFlat(True)
        self.create_level_butt.setObjectName("create_level_butt")
        self.records_butt = QtWidgets.QPushButton(parent=self.centralwidget)
        self.records_butt.setGeometry(QtCore.QRect(500, 530, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.records_butt.setFont(font)
        self.records_butt.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.records_butt.setStyleSheet("color: rgb(255, 148, 60);")
        self.records_butt.setFlat(True)
        self.records_butt.setObjectName("records_butt")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(510, 150, 351, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(48)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Blind "))
        self.exit_butt.setText(_translate("MainWindow", "Выход"))
        self.new_game_butt.setText(_translate("MainWindow", "Начать игру"))
        self.create_level_butt.setText(_translate("MainWindow", "Создать новый уровень"))
        self.records_butt.setText(_translate("MainWindow", "Рекорды"))
        self.label_2.setText(_translate("MainWindow", "Typing"))
